// <auto-generated />
using System;
using GlicoNutri.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlicoNutri.Api.Data.Migrations
{
    [DbContext(typeof(GlicoNutriDbContext))]
    [Migration("20260912055952_FavoritosEMidiaDoConteudo")]
    partial class FavoritosEMidiaDoConteudo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlicoNutri.Api.Models.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("DiasSemana")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dias_semana");

                    b.Property<TimeOnly?>("Horario1")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_1");

                    b.Property<TimeOnly?>("Horario2")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_2");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<long>("TipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_alertas_paciente_id");

                    b.HasIndex("TipoId")
                        .HasDatabaseName("ix_alertas_tipo_id");

                    b.ToTable("alertas", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Alimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<double?>("CaloriasPor100g")
                        .HasColumnType("double precision")
                        .HasColumnName("calorias_por_100g");

                    b.Property<double?>("CarboidratosPor100g")
                        .HasColumnType("double precision")
                        .HasColumnName("carboidratos_por_100g");

                    b.Property<double?>("FibrasPor100g")
                        .HasColumnType("double precision")
                        .HasColumnName("fibras_por_100g");

                    b.Property<long>("FonteId")
                        .HasColumnType("bigint")
                        .HasColumnName("fonte_id");

                    b.Property<long?>("FonteIndiceGlicemicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("fonte_indice_glicemico_id");

                    b.Property<string>("GrupoAlimentar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grupo_alimentar");

                    b.Property<int?>("IndiceGlicemico")
                        .HasColumnType("integer")
                        .HasColumnName("indice_glicemico");

                    b.Property<double?>("LipidiosPor100g")
                        .HasColumnType("double precision")
                        .HasColumnName("lipidios_por_100g");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<double?>("ProteinasPor100g")
                        .HasColumnType("double precision")
                        .HasColumnName("proteinas_por_100g");

                    b.HasKey("Id");

                    b.HasIndex("FonteId")
                        .HasDatabaseName("ix_alimentos_fonte_id");

                    b.HasIndex("FonteIndiceGlicemicoId")
                        .HasDatabaseName("ix_alimentos_fonte_indice_glicemico_id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_alimentos_nome");

                    b.ToTable("alimentos", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.ConteudoEducativo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("AutorId")
                        .HasColumnType("bigint")
                        .HasColumnName("autor_id");

                    b.Property<string>("Corpo")
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<long>("TipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlMidia")
                        .HasColumnType("text")
                        .HasColumnName("url_midia");

                    b.HasKey("Id");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_conteudos_educativos_autor_id");

                    b.HasIndex("TipoId")
                        .HasDatabaseName("ix_conteudos_educativos_tipo_id");

                    b.ToTable("conteudos_educativos", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.DistribuicaoMacronutrientes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("CarboidratosGramas")
                        .HasColumnType("double precision")
                        .HasColumnName("carboidratos_gramas");

                    b.Property<double>("CarboidratosPercentual")
                        .HasColumnType("double precision")
                        .HasColumnName("carboidratos_percentual");

                    b.Property<double?>("LipidiosGramas")
                        .HasColumnType("double precision")
                        .HasColumnName("lipidios_gramas");

                    b.Property<double>("LipidiosPercentual")
                        .HasColumnType("double precision")
                        .HasColumnName("lipidios_percentual");

                    b.Property<long>("PlanoAlimentarId")
                        .HasColumnType("bigint")
                        .HasColumnName("plano_alimentar_id");

                    b.Property<double?>("ProteinasGramas")
                        .HasColumnType("double precision")
                        .HasColumnName("proteinas_gramas");

                    b.Property<double>("ProteinasPercentual")
                        .HasColumnType("double precision")
                        .HasColumnName("proteinas_percentual");

                    b.Property<double?>("TotalCaloriasPrescritas")
                        .HasColumnType("double precision")
                        .HasColumnName("total_calorias_prescritas");

                    b.HasKey("Id");

                    b.HasIndex("PlanoAlimentarId")
                        .IsUnique()
                        .HasDatabaseName("ix_distribuicao_macronutrientes_plano_alimentar_id");

                    b.ToTable("distribuicao_macronutrientes", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.FavoritoConteudo", b =>
                {
                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<long>("ConteudoId")
                        .HasColumnType("bigint")
                        .HasColumnName("conteudo_id");

                    b.Property<DateTime>("DataFavoritado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_favoritado")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PacienteId", "ConteudoId");

                    b.HasIndex("ConteudoId")
                        .HasDatabaseName("ix_favoritos_conteudo_conteudo_id");

                    b.ToTable("favoritos_conteudo", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.FavoritoReceita", b =>
                {
                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("receita_id");

                    b.Property<DateTime>("DataFavoritado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_favoritado")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PacienteId", "ReceitaId");

                    b.HasIndex("ReceitaId")
                        .HasDatabaseName("ix_favoritos_receita_receita_id");

                    b.ToTable("favoritos_receita", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.HistoricoAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlertaId")
                        .HasColumnType("bigint")
                        .HasColumnName("alerta_id");

                    b.Property<DateTime?>("DataHoraAtendimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atendimento");

                    b.Property<DateTime>("DataHoraDisparo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_disparo");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_erro");

                    b.Property<long>("StatusEnvioId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_envio_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId")
                        .HasDatabaseName("ix_historico_alertas_alerta_id");

                    b.HasIndex("StatusEnvioId", "DataHoraDisparo")
                        .HasDatabaseName("ix_historico_alertas_status_envio_id_data_hora_disparo");

                    b.ToTable("historico_alertas", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.IngredienteReceita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("alimento_id");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double precision")
                        .HasColumnName("quantidade");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("receita_id");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId")
                        .HasDatabaseName("ix_ingredientes_receita_alimento_id");

                    b.HasIndex("ReceitaId")
                        .HasDatabaseName("ix_ingredientes_receita_receita_id");

                    b.ToTable("ingredientes_receita", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.ItemPlanoAlimentar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("alimento_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("Dia")
                        .HasColumnType("integer")
                        .HasColumnName("dia");

                    b.Property<TimeOnly?>("Horario")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario");

                    b.Property<long>("PlanoAlimentarId")
                        .HasColumnType("bigint")
                        .HasColumnName("plano_alimentar_id");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double precision")
                        .HasColumnName("quantidade");

                    b.Property<string>("Refeicao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("refeicao");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId")
                        .HasDatabaseName("ix_itens_plano_alimentar_alimento_id");

                    b.HasIndex("PlanoAlimentarId")
                        .HasDatabaseName("ix_itens_plano_alimentar_plano_alimentar_id");

                    b.ToTable("itens_plano_alimentar", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.NecessidadeEnergetica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateOnly>("DataCalculo")
                        .HasColumnType("date")
                        .HasColumnName("data_calculo");

                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint")
                        .HasColumnName("formula_id");

                    b.Property<long>("NivelAtividadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("nivel_atividade_id");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("objetivo");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<double>("ValorKcal")
                        .HasColumnType("double precision")
                        .HasColumnName("valor_kcal");

                    b.HasKey("Id");

                    b.HasIndex("FormulaId")
                        .HasDatabaseName("ix_necessidades_energeticas_formula_id");

                    b.HasIndex("NivelAtividadeId")
                        .HasDatabaseName("ix_necessidades_energeticas_nivel_atividade_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_necessidades_energeticas_paciente_id");

                    b.ToTable("necessidades_energeticas", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.NutricionistaPaciente", b =>
                {
                    b.Property<long>("NutricionistaId")
                        .HasColumnType("bigint")
                        .HasColumnName("nutricionista_id");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataVinculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vinculo")
                        .HasDefaultValueSql("now()");

                    b.HasKey("NutricionistaId", "PacienteId");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_nutricionista_paciente_paciente_id");

                    b.ToTable("nutricionista_paciente", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.PlanoAlimentar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<long>("NutricionistaId")
                        .HasColumnType("bigint")
                        .HasColumnName("nutricionista_id");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("objetivo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<double?>("TotalCaloriasPrescritas")
                        .HasColumnType("double precision")
                        .HasColumnName("total_calorias_prescritas");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId")
                        .HasDatabaseName("ix_planos_alimentares_nutricionista_id");

                    b.HasIndex("PacienteId")
                        .IsUnique()
                        .HasDatabaseName("ix_planos_alimentares_paciente_ativo_unico")
                        .HasFilter("ativo = true");

                    b.ToTable("planos_alimentares", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("text")
                        .HasColumnName("instrucoes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<long>("NutricionistaId")
                        .HasColumnType("bigint")
                        .HasColumnName("nutricionista_id");

                    b.Property<int?>("Porcoes")
                        .HasColumnType("integer")
                        .HasColumnName("porcoes");

                    b.Property<int?>("TempoPreparo")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_preparo");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId")
                        .HasDatabaseName("ix_receitas_nutricionista_id");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.ContextoGlicemia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_contextos_glicemia_codigo");

                    b.ToTable("contextos_glicemia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "JEJUM",
                            Descricao = "Jejum"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "PRE_REFEICAO",
                            Descricao = "Pré-refeição"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "POS_REFEICAO",
                            Descricao = "Pós-refeição"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "ANTES_DE_DORMIR",
                            Descricao = "Ao deitar"
                        },
                        new
                        {
                            Id = 5L,
                            Ativo = true,
                            Codigo = "OUTRO",
                            Descricao = "Outro"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.EstadoEmocional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_emocionais_codigo");

                    b.ToTable("estados_emocionais", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "FELIZ",
                            Descricao = "Feliz"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "TRANQUILO",
                            Descricao = "Tranquilo"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "ANSIOSO",
                            Descricao = "Ansioso"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "TRISTE",
                            Descricao = "Triste"
                        },
                        new
                        {
                            Id = 5L,
                            Ativo = true,
                            Codigo = "IRRITADO",
                            Descricao = "Irritado"
                        },
                        new
                        {
                            Id = 6L,
                            Ativo = true,
                            Codigo = "ESTRESSADO",
                            Descricao = "Estressado"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.FonteAlimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_fontes_alimento_codigo");

                    b.ToTable("fontes_alimento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "TACO",
                            Descricao = "Tabela TACO / IBGE"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "MANUAL",
                            Descricao = "Cadastro manual"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.FonteIndiceGlicemico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_fontes_indice_glicemico_codigo");

                    b.ToTable("fontes_indice_glicemico", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "TABELA_INTERNACIONAL",
                            Descricao = "International Tables of Glycemic Index and Glycemic Load Values 2021"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "PROFISSIONAL",
                            Descricao = "Informado pelo nutricionista"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.FormulaEnergetica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_formulas_energeticas_codigo");

                    b.ToTable("formulas_energeticas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "HARRIS_BENEDICT",
                            Descricao = "Harris-Benedict (revisão de Roza e Shizgal, 1984)"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "MIFFLIN_ST_JEOR",
                            Descricao = "Mifflin-St Jeor"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.NivelAtividade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<double>("Fator")
                        .HasColumnType("double precision")
                        .HasColumnName("fator");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_niveis_atividade_codigo");

                    b.ToTable("niveis_atividade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "SEDENTARIO",
                            Descricao = "Sedentário",
                            Fator = 1.2
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "LEVEMENTE_ATIVO",
                            Descricao = "Levemente ativo",
                            Fator = 1.375
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "MODERADAMENTE_ATIVO",
                            Descricao = "Moderadamente ativo",
                            Fator = 1.55
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "MUITO_ATIVO",
                            Descricao = "Muito ativo",
                            Fator = 1.7250000000000001
                        },
                        new
                        {
                            Id = 5L,
                            Ativo = true,
                            Codigo = "EXTREMAMENTE_ATIVO",
                            Descricao = "Extremamente ativo",
                            Fator = 1.8999999999999999
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.PerfilUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_usuario_codigo");

                    b.ToTable("perfis_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "PACIENTE",
                            Descricao = "Paciente"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "NUTRICIONISTA",
                            Descricao = "Nutricionista"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "ADMINISTRADOR",
                            Descricao = "Administrador"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.SexoBiologico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_sexos_biologicos_codigo");

                    b.ToTable("sexos_biologicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "MASCULINO",
                            Descricao = "Masculino"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "FEMININO",
                            Descricao = "Feminino"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.StatusEnvio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_status_envio_codigo");

                    b.ToTable("status_envio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "PENDENTE",
                            Descricao = "Notificado; aguardando ação do paciente"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "ATENDIDO",
                            Descricao = "Paciente realizou o registro correspondente"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "REAGENDADO",
                            Descricao = "Paciente pediu novo lembrete em 15 minutos"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "FALHOU",
                            Descricao = "Não entregue ou expirado pela janela de 2 horas (RN35)"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.TipoAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_alerta_codigo");

                    b.ToTable("tipos_alerta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "GLICEMIA",
                            Descricao = "Glicemia"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "MEDICAMENTO",
                            Descricao = "Medicamento"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "REFEICAO",
                            Descricao = "Refeição"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "PERSONALIZADO",
                            Descricao = "Personalizado"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.TipoConteudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_conteudo_codigo");

                    b.ToTable("tipos_conteudo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "ARTIGO",
                            Descricao = "Artigo"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "DICA",
                            Descricao = "Dica"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "RECEITA",
                            Descricao = "Receita"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "VIDEO",
                            Descricao = "Vídeo"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Referencia.TipoDiabetes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_diabetes_codigo");

                    b.ToTable("tipos_diabetes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            Codigo = "TIPO_1",
                            Descricao = "Diabetes tipo 1"
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            Codigo = "TIPO_2",
                            Descricao = "Diabetes tipo 2"
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            Codigo = "GESTACIONAL",
                            Descricao = "Diabetes gestacional"
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            Codigo = "MODY",
                            Descricao = "MODY (Maturity Onset Diabetes of the Young)"
                        },
                        new
                        {
                            Id = 5L,
                            Ativo = true,
                            Codigo = "PRE_DIABETES",
                            Descricao = "Pré-diabetes"
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.RegistroAntropometrico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("double precision")
                        .HasColumnName("altura");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<double?>("CircunferenciaAbdominal")
                        .HasColumnType("double precision")
                        .HasColumnName("circunferencia_abdominal");

                    b.Property<double?>("CircunferenciaBraco")
                        .HasColumnType("double precision")
                        .HasColumnName("circunferencia_braco");

                    b.Property<double?>("CircunferenciaCintura")
                        .HasColumnType("double precision")
                        .HasColumnName("circunferencia_cintura");

                    b.Property<double?>("CircunferenciaQuadril")
                        .HasColumnType("double precision")
                        .HasColumnName("circunferencia_quadril");

                    b.Property<string>("ClassificacaoImc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classificacao_imc");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<double?>("Imc")
                        .HasColumnType("double precision")
                        .HasColumnName("imc");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision")
                        .HasColumnName("peso");

                    b.Property<double?>("Rcq")
                        .HasColumnType("double precision")
                        .HasColumnName("rcq");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "DataHora")
                        .HasDatabaseName("ix_registros_antropometricos_paciente_id_data_hora");

                    b.ToTable("registros_antropometricos", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.RegistroEmocional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("EstadoEmocionalId")
                        .HasColumnType("bigint")
                        .HasColumnName("estado_emocional_id");

                    b.Property<int>("Intensidade")
                        .HasColumnType("integer")
                        .HasColumnName("intensidade");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoEmocionalId")
                        .HasDatabaseName("ix_registros_emocionais_estado_emocional_id");

                    b.HasIndex("PacienteId", "DataHora")
                        .HasDatabaseName("ix_registros_emocionais_paciente_id_data_hora");

                    b.ToTable("registros_emocionais", null, t =>
                        {
                            t.HasCheckConstraint("ck_registros_emocionais_intensidade", "intensidade BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.RegistroGlicemia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("ContextoId")
                        .HasColumnType("bigint")
                        .HasColumnName("contexto_id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<bool>("ForaDoAlvo")
                        .HasColumnType("boolean")
                        .HasColumnName("fora_do_alvo");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContextoId")
                        .HasDatabaseName("ix_registros_glicemia_contexto_id");

                    b.HasIndex("PacienteId", "DataHora")
                        .HasDatabaseName("ix_registros_glicemia_paciente_id_data_hora");

                    b.ToTable("registros_glicemia", null, t =>
                        {
                            t.HasCheckConstraint("ck_registros_glicemia_valor", "valor >= 0 AND valor <= 600");
                        });
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.ResumoClinicoPaciente", b =>
                {
                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<int>("AlertasPendentesCount")
                        .HasColumnType("integer")
                        .HasColumnName("alertas_pendentes_count");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<int?>("DiasSemRegistroGlicemia")
                        .HasColumnType("integer")
                        .HasColumnName("dias_sem_registro_glicemia");

                    b.Property<double?>("MediaGlicemia7Dias")
                        .HasColumnType("double precision")
                        .HasColumnName("media_glicemia_7dias");

                    b.Property<double?>("PercentualNoAlvo7Dias")
                        .HasColumnType("double precision")
                        .HasColumnName("percentual_no_alvo_7dias");

                    b.Property<bool>("PlanoAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("plano_ativo");

                    b.Property<string>("UltimaClassificacaoImc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ultima_classificacao_imc");

                    b.Property<DateTime?>("UltimaDataAntropometria")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_data_antropometria");

                    b.Property<long?>("UltimaGlicemiaContextoId")
                        .HasColumnType("bigint")
                        .HasColumnName("ultima_glicemia_contexto_id");

                    b.Property<DateTime?>("UltimaGlicemiaData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_glicemia_data");

                    b.Property<double?>("UltimaGlicemiaValor")
                        .HasColumnType("double precision")
                        .HasColumnName("ultima_glicemia_valor");

                    b.Property<double?>("UltimoImc")
                        .HasColumnType("double precision")
                        .HasColumnName("ultimo_imc");

                    b.HasKey("PacienteId");

                    b.HasIndex("UltimaGlicemiaContextoId");

                    b.ToTable((string)null);

                    b.ToView("resumo_clinico_paciente", (string)null);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int>("NivelBloqueio")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_bloqueio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("perfil_id");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<bool>("SenhaProvisoria")
                        .HasColumnType("boolean")
                        .HasColumnName("senha_provisoria");

                    b.Property<int>("TentativasInvalidas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_invalidas");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuarios_perfil_id");

                    b.ToTable("usuarios", (string)null);

                    b.HasDiscriminator<long>("PerfilId");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Administrador", b =>
                {
                    b.HasBaseType("GlicoNutri.Api.Models.Usuario");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_acesso");

                    b.HasDiscriminator().HasValue(3L);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Nutricionista", b =>
                {
                    b.HasBaseType("GlicoNutri.Api.Models.Usuario");

                    b.Property<string>("Crn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crn");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("especialidade");

                    b.Property<string>("Telefone")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasIndex("Crn")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_crn");

                    b.HasDiscriminator().HasValue(2L);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Paciente", b =>
                {
                    b.HasBaseType("GlicoNutri.Api.Models.Usuario");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<double?>("GlicemiaMaxAlvo")
                        .HasColumnType("double precision")
                        .HasColumnName("glicemia_max_alvo");

                    b.Property<double?>("GlicemiaMinAlvo")
                        .HasColumnType("double precision")
                        .HasColumnName("glicemia_min_alvo");

                    b.Property<string>("MedicacaoEmUso")
                        .HasColumnType("text")
                        .HasColumnName("medicacao_em_uso");

                    b.Property<string>("ObservacoesClinicas")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_clinicas");

                    b.Property<long>("SexoId")
                        .HasColumnType("bigint")
                        .HasColumnName("sexo_id");

                    b.Property<string>("Telefone")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<long>("TipoDiabetesId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_diabetes_id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_cpf");

                    b.HasIndex("SexoId")
                        .HasDatabaseName("ix_usuarios_sexo_id");

                    b.HasIndex("TipoDiabetesId")
                        .HasDatabaseName("ix_usuarios_tipo_diabetes_id");

                    b.HasDiscriminator().HasValue(1L);
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Alerta", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("Alertas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alertas_usuarios_paciente_id");

                    b.HasOne("GlicoNutri.Api.Models.Referencia.TipoAlerta", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alertas_tipos_alerta_tipo_id");

                    b.Navigation("Paciente");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Alimento", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Referencia.FonteAlimento", "Fonte")
                        .WithMany()
                        .HasForeignKey("FonteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alimentos_fontes_alimento_fonte_id");

                    b.HasOne("GlicoNutri.Api.Models.Referencia.FonteIndiceGlicemico", "FonteIndiceGlicemico")
                        .WithMany()
                        .HasForeignKey("FonteIndiceGlicemicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_alimentos_fontes_indice_glicemico_fonte_indice_glicemico_id");

                    b.Navigation("Fonte");

                    b.Navigation("FonteIndiceGlicemico");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.ConteudoEducativo", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Usuario", "Autor")
                        .WithMany("ConteudosPublicados")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conteudos_educativos_usuarios_autor_id");

                    b.HasOne("GlicoNutri.Api.Models.Referencia.TipoConteudo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conteudos_educativos_tipos_conteudo_tipo_id");

                    b.Navigation("Autor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.DistribuicaoMacronutrientes", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.PlanoAlimentar", "PlanoAlimentar")
                        .WithOne("Distribuicao")
                        .HasForeignKey("GlicoNutri.Api.Models.DistribuicaoMacronutrientes", "PlanoAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_distribuicao_macronutrientes_planos_alimentares_plano_alime~");

                    b.Navigation("PlanoAlimentar");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.FavoritoConteudo", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.ConteudoEducativo", "Conteudo")
                        .WithMany()
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoritos_conteudo_conteudos_educativos_conteudo_id");

                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoritos_conteudo_usuarios_paciente_id");

                    b.Navigation("Conteudo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.FavoritoReceita", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoritos_receita_usuarios_paciente_id");

                    b.HasOne("GlicoNutri.Api.Models.Receita", "Receita")
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoritos_receita_receitas_receita_id");

                    b.Navigation("Paciente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.HistoricoAlerta", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Alerta", "Alerta")
                        .WithMany("Historico")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_alertas_alertas_alerta_id");

                    b.HasOne("GlicoNutri.Api.Models.Referencia.StatusEnvio", "StatusEnvio")
                        .WithMany()
                        .HasForeignKey("StatusEnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historico_alertas_status_envio_status_envio_id");

                    b.Navigation("Alerta");

                    b.Navigation("StatusEnvio");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.IngredienteReceita", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Alimento", "Alimento")
                        .WithMany("Ingredientes")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredientes_receita_alimentos_alimento_id");

                    b.HasOne("GlicoNutri.Api.Models.Receita", "Receita")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredientes_receita_receitas_receita_id");

                    b.Navigation("Alimento");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.ItemPlanoAlimentar", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Alimento", "Alimento")
                        .WithMany("ItensPlano")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_plano_alimentar_alimentos_alimento_id");

                    b.HasOne("GlicoNutri.Api.Models.PlanoAlimentar", "PlanoAlimentar")
                        .WithMany("Itens")
                        .HasForeignKey("PlanoAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_plano_alimentar_planos_alimentares_plano_alimentar_id");

                    b.Navigation("Alimento");

                    b.Navigation("PlanoAlimentar");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.NecessidadeEnergetica", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Referencia.FormulaEnergetica", "Formula")
                        .WithMany()
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_necessidades_energeticas_formulas_energeticas_formula_id");

                    b.HasOne("GlicoNutri.Api.Models.Referencia.NivelAtividade", "NivelAtividade")
                        .WithMany()
                        .HasForeignKey("NivelAtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_necessidades_energeticas_niveis_atividade_nivel_atividade_id");

                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("NecessidadesEnergeticas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_necessidades_energeticas_usuarios_paciente_id");

                    b.Navigation("Formula");

                    b.Navigation("NivelAtividade");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.NutricionistaPaciente", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Nutricionista", "Nutricionista")
                        .WithMany("Vinculos")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nutricionista_paciente_usuarios_nutricionista_id");

                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("Vinculos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nutricionista_paciente_usuarios_paciente_id");

                    b.Navigation("Nutricionista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.PlanoAlimentar", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Nutricionista", "Nutricionista")
                        .WithMany("PlanosElaborados")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planos_alimentares_usuarios_nutricionista_id");

                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("Planos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planos_alimentares_usuarios_paciente_id");

                    b.Navigation("Nutricionista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Receita", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Nutricionista", "Nutricionista")
                        .WithMany("Receitas")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receitas_usuarios_nutricionista_id");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.RegistroAntropometrico", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("RegistrosAntropometricos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_antropometricos_usuarios_paciente_id");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.RegistroEmocional", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Referencia.EstadoEmocional", "EstadoEmocional")
                        .WithMany()
                        .HasForeignKey("EstadoEmocionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_emocionais_estados_emocionais_estado_emocional_id");

                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("RegistrosEmocionais")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_emocionais_usuarios_paciente_id");

                    b.Navigation("EstadoEmocional");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.RegistroGlicemia", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Referencia.ContextoGlicemia", "Contexto")
                        .WithMany()
                        .HasForeignKey("ContextoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_glicemia_contextos_glicemia_contexto_id");

                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithMany("RegistrosGlicemia")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_glicemia_usuarios_paciente_id");

                    b.Navigation("Contexto");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.ResumoClinicoPaciente", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Paciente", "Paciente")
                        .WithOne("Resumo")
                        .HasForeignKey("GlicoNutri.Api.Models.ResumoClinicoPaciente", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlicoNutri.Api.Models.Referencia.ContextoGlicemia", "UltimaGlicemiaContexto")
                        .WithMany()
                        .HasForeignKey("UltimaGlicemiaContextoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paciente");

                    b.Navigation("UltimaGlicemiaContexto");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Usuario", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Referencia.PerfilUsuario", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_perfis_usuario_perfil_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Paciente", b =>
                {
                    b.HasOne("GlicoNutri.Api.Models.Referencia.SexoBiologico", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_sexos_biologicos_sexo_id");

                    b.HasOne("GlicoNutri.Api.Models.Referencia.TipoDiabetes", "TipoDiabetes")
                        .WithMany()
                        .HasForeignKey("TipoDiabetesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_tipos_diabetes_tipo_diabetes_id");

                    b.Navigation("Sexo");

                    b.Navigation("TipoDiabetes");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Alerta", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Alimento", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("ItensPlano");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.PlanoAlimentar", b =>
                {
                    b.Navigation("Distribuicao");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Receita", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Usuario", b =>
                {
                    b.Navigation("ConteudosPublicados");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Nutricionista", b =>
                {
                    b.Navigation("PlanosElaborados");

                    b.Navigation("Receitas");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("GlicoNutri.Api.Models.Paciente", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("NecessidadesEnergeticas");

                    b.Navigation("Planos");

                    b.Navigation("RegistrosAntropometricos");

                    b.Navigation("RegistrosEmocionais");

                    b.Navigation("RegistrosGlicemia");

                    b.Navigation("Resumo");

                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
